# Runs tests on every pull request creation and update event.
#
# N.B. The test job can be referenced as a required status check in a
# repository's branch protection rules, meaning you will not be able to merge to
# the target branch this job fails.

name: Test PRs to acc

on:
  pull_request:
    branches: [acc]
    types: [opened, edited, synchronize]

jobs:
  test-acc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm install
      - run: npm run lint -- --max-warnings=0
      - run: npm test
