name: Python App Deployer

on:
  push:
    inputs:
      organization:
        description: Name of the TFC organization you're deploying to
        required: false
        default: guidion
        type: string
      workspace:
        description: Name of the TFC workspace we're using
        required: true
        type: string
      approvers:
        description: CSV of people allowed to approve this plan
        required: false
        default: afrazkhan
        type: string
      source_dir:
        description: Name of the directory holding the source to be deployed
        required: false
        type: string
        default: dist
    secrets:
      tfc_api_token:
        description: Token used to talk to Terraform Cloud
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install dependencies and run tests
        run: |
          cd dist
          pip install -r requirements.txt --target libs
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform
          path: |
            dist
            *.tf

  deploy_prod:
    needs: build_and_test
    permissions:
      issues: write
      contents: read
      pull-requests: write
    uses: guidion-digital/terrappy/.github/workflows/tfc-deploy.yaml@beta0.0.6
    with:
      organization: guidion
      workspace: ${{ inputs.workspace }}
      approvers: ${{ inputs.approvers }}
      source_dir: ${{ inputs.source_dir }}
    secrets:
      tfc_api_token: ${{ secrets.TFC_API_TOKEN_PROD }}
