name: Python App Deployer

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install dependencies and run tests
        run: |
          cd dist
          pip install -r requirements.txt --target libs
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform
          path: |
            dist
            *.tf
          retention-days: 2

  deploy_prod:
    needs: build_and_test
    permissions:
      issues: write
      contents: read
      pull-requests: write
    uses: guidion-digital/terrappy/.github/workflows/tfc-deploy.yaml@beta0.0.8
    with:
      organization: guidion
      workspace: FILL ME IN
      approvers: (OPTIONAL) FILL ME IN
      source_dir: (OPTIONAL) FILL ME IN
      retention-days: (OPTIONAL) FILL ME IN
    secrets:
      tfc_api_token: ${{ secrets.TFC_API_TOKEN_PROD }}
