# TODO: This is also nice for skipping certain unecessary runs
# https://github.com/marketplace/actions/skip-duplicate-actions

name: Python App Environment Deployer

on:
  push:
    branches:
      - acc

concurrency:
  group: acc

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    environment: acc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install dependencies and run tests
        run: |
          cd dist
          pip install -r requirements.txt --target libs
      - name: Run tests
        run: echo 'TODO :)'
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform
          path: |
            dist
            *.tf
          retention-days: 2

  deploy:
    needs: build_and_test
    secrets: inherit
    permissions:
      issues: write
      contents: read
      pull-requests: write
    uses: guidion-digital/terrappy/.github/workflows/tfc-deploy.yaml@beta0.0.25
    with:
      environment_name: acc
