name: Test PRs to acc

on:
  pull_request:
    branches: [$default-branch]
    types: [opened, edited, synchronize]

jobs:
  plan-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: "latest"
      - name: Install tflocal
        run: pip install terraform-local
      - name: Test example [FILL ME IN]
        run: |
          cd examples/[FILL ME IN]
          tflocal init
          tflocal plan
