# Reusable workflow, intended for use in both deploy workflows, and PR workflows

name: Run tests and build

on:
  workflow_call:
    inputs:
      environment_name:
        description: The Github environment containing all the variables needed
        required: true
        type: string
      concurrency_name:
        description: Concurrency name used. Falls back to environment name if not set
        required: false
        type: string
      retention-days:
        description: How long to keep the build artifacts
        required: false
        type: number
        default: 2
      disable_artefacts:
        description: Whether to upload artefacts for deploying
        required: false
        type: boolean
        default: false

jobs:
  test_and_build:
    name: Test and Build
    environment: "${{ inputs.environment_name }}-build"
    concurrency:
      group: ${{ inputs.concurrency_name || inputs.environment_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    # env: USE / DELETE AS NECESSARY
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm install
      - name: Lint
        run: npm run lint -- --max-warnings=0
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Archive artifacts
        if: ${{ inputs.disable_artefacts == false }}
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform
          path: |
            dist
            *.tf
          retention-days: ${{ inputs.retention-days }}
